[versions]
androidxUiTest = "1.9.0"
koin = "4.1.0"
ktorClient = "3.2.3"
kotlinxCoroutines = "1.10.2"
coil3 = "3.3.0"
lifecycleRuntimeAndroid = "2.9.3"
lifecycle = "2.9.3"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.8" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = "2.2.10" }

[libraries]
androidxUiTestJunit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref="androidxUiTest" }
androidxUiTestManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref="androidxUiTest" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
coil-compose-core = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coil3" }
coil-network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil3" }
coil-mp = { module = "io.coil-kt.coil3:coil", version.ref = "coil3" }
koinAndroid = { module = "io.insert-koin:koin-android", version.ref="koin" }
koinComposeViewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koinCore = { module = "io.insert-koin:koin-core", version.ref="koin" }
koinTest = { module = "io.insert-koin:koin-test", version.ref="koin" }
ktorClient = { module = "io.ktor:ktor-client-android", version.ref="ktorClient" }
ktorClientJs = { module = "io.ktor:ktor-client-js", version.ref="ktorClient" }
ktorClientContentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref="ktorClient" }
ktorClientCore = { module = "io.ktor:ktor-client-core", version.ref="ktorClient" }
ktorClientIos = { module = "io.ktor:ktor-client-darwin", version.ref="ktorClient" }
ktorClientWasmJs = { module = "io.ktor:ktor-client-js-wasm-js", version.ref = "ktorClient" }
ktorClientJvm = { module = "io.ktor:ktor-client-jvm", version.ref="ktorClient" }
ktorClientJava = { module = "io.ktor:ktor-client-java", version.ref="ktorClient" }
ktorClientJson = { module = "io.ktor:ktor-client-json", version.ref="ktorClient" }
ktorClientLogging = { module = "io.ktor:ktor-client-logging", version.ref="ktorClient" }
ktorSerializationKotlinxJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref="ktorClient" }
kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref="kotlinxCoroutines" }
kotlinxCoroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref="kotlinxCoroutines" }
kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref="kotlinxCoroutines" }
kotlinxSerializationCore = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version="1.9.0" }
lifecycle-runtime-android = { module = "androidx.lifecycle:lifecycle-runtime-android", version.ref = "lifecycleRuntimeAndroid" }
multiplatformSettings = { module = "com.russhwolf:multiplatform-settings-no-arg", version="1.3.0" }
lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }

# build-logic
build-gradle-plugin = { module = "com.android.tools.build:gradle", version = "8.12.2" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version = "2.2.10" }
compose-compiler-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version = "2.2.10" }